apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-stress
spec:
  replicas: 8
  selector:
    matchLabels:
      app: memory-stress
  template:
    metadata:
      labels:
        app: memory-stress
    spec:
      containers:
      - name: memory-stress
        image: busybox:1.36
        command:
        - /bin/sh
        - -c
        - |
          echo "Allocating 700MB RAM..."
          dd if=/dev/zero of=/cache/memory bs=1M count=700
          echo "Memory allocated. Sleeping..."
          sleep 3600
        volumeMounts:
        - name: ramdisk
          mountPath: /cache
      volumes:
      - name: ramdisk
        emptyDir:
          medium: Memory